apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service-grpc
  template:
    metadata:
      labels:
        app: product-service-grpc
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: product-service-grpc
        image: sandro21/product-service-grpc-proto
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
          limits:
            cpu: 2m
            memory: 20Mi
        
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-grpc
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
      nodePort: 30080  
  selector:
    app: product-service-grpc

